BoxLayout:
    orientation: 'horizontal'
    TextInput:
        id: input_number
        multiline: False

    Button:
        text: 'Up'
        on_press: app.handle_increment(1)


    Button:
        text: 'Down'
        on_press: app.handle_increment(-1)


    Button:
        text: 'Convert m to km'
        on_press: app.handle_convert(int(input_number.text))

    Label:
        color: (255,255,0,1)
        id: output_label
